// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import (
	"github.com/gogf/gf/os/gtime"
)

// Project is the golang structure for table project.
type Project struct {
	Id   int    `orm:"id,primary" json:"id"`   //
	Name string `orm:"name"       json:"name"` //
	Age  int    `orm:"age"        json:"age"`  // 年龄
}

// Sqlaudit is the golang structure for table sqlaudit.
type Sqlaudit struct {
	Id   int         `orm:"id,primary" json:"id"`   //
	Cost int         `orm:"cost"       json:"cost"` //
	Time *gtime.Time `orm:"time"       json:"time"` //
	Err  string      `orm:"err"        json:"err"`  //
	Sql  string      `orm:"sql"        json:"sql"`  //
}

// User is the golang structure for table user.
type User struct {
	Id        uint        `orm:"id,primary" json:"id"`                   //
	Name      string      `orm:"name"       json:"name"`                 //
	Age       int         `orm:"age"       json:"age"`                   //
	CreatedAt *gtime.Time `orm:"created_at" json:"created_at"`           //
	UpdatedAt *gtime.Time `orm:"updated_at" json:"updated_at"`           //
	DeletedAt *gtime.Time `orm:"deleted_at" json:"deleted_at,omitempty"` //
	Version   int         `orm:"version"    json:"version"`              //
}

// UserDetail is the golang structure for table user_detail.
type UserDetail struct {
	Uid     uint   `orm:"uid,primary" json:"uid"`     //
	Address string `orm:"address"     json:"address"` //
}

// UserScore is the golang structure for table user_score.
type UserScore struct {
	Id     uint   `orm:"id,primary" json:"id"`     //
	Uid    uint   `orm:"uid"        json:"uid"`    //
	Score  uint   `orm:"score"      json:"score"`  //
	Course string `orm:"course"     json:"course"` //
}
