# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
    #服务
	logPath             = "/tmp/log/gf-app"                 # 日志文件存储目录路径，建议使用绝对路径。默认为空，表示关闭
    logStdout           = false               # 日志是否输出到终端。默认为true
    errorStack          = true               # 当Server捕获到异常时是否记录堆栈信息到日志中。默认为true
    errorLogEnabled     = true               # 是否记录异常日志信息到日志中。默认为true
    errorLogPattern     = "error-{Ymd}.log"  # 异常错误日志文件格式。默认为"error-{Ymd}.log"
    accessLogEnabled    = true              # 是否记录访问日志。默认为false
    accessLogPattern    = "access-{Ymd}.log" # 访问日志文件格式。默认为"access-{Ymd}.log"
    # Sessions配置
    sessionMaxAge       = "24h"              # Session有效期。默认为24小时
    sessionIdName       = "gfsessionid"      # SessionId的键名名称。默认为gfsessionid
    sessionCookieOutput = true               # Session特性开启时，是否将SessionId返回到Cookie中。默认true
#   sessionPath         = "/tmp/gsessions"   # Session存储的文件目录路径。默认为当前系统临时目录下的gsessions目录

    dumpRouterMap = false

# Logger.
[logger]
    Path        = "/tmp/log/gf-app"
    prefix      = ""
    Level       = "all"
    Stdout      = true
#     header      = false
#      CtxKeys =   ["TraceID"]
    [logger.info]
            path   = "/tmp/log/gf-app/biz"
            file   = "{Y-m-d}.log" # 日志
            level  = "info"
            stdout = false
    [logger.error]
            path   = "/tmp/log/gf-app/biz"
            file   = "error-{Y-m-d}.log" # 日志
            level  = "error"
            stdout = true
# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  = ["{{", "}}"]
    autoncode   = true

# Database.
[database]
# 	type = "MyDriver"
    link  = "mysql:write:write@tcp(43.247.184.35:8899)/xpaas"
    debug = true
    timeMaintainDisabled = false
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/gf-app/sql"
        Level  = "all"
        Stdout = true

[redis]
#    default = "192.168.4.119:6379,1,root@123456?idleTimeout=600"
    default = "59.110.125.77:30479,5,havzMSYc3aBZXOjpG3?idleTimeout=600"
    cache   = "192.168.4.119:6379,1,123456?idleTimeout=600"
[appInfo]
    name="paas"
    enableEs=false
[esConfig]
    urls = ["http://192.168.4.110:9200"]
    userName = "elastic"
    pwd = "elastic"
    isSniff = false
    healthCheckInterval = 30
    maxRetries = 5

[path2Model]
#   solution= "Solution"
#   controlinfo="ControlInfo"
#    #派生实体，后台无表，是对后台实体的组合
#    solutionwithcontrolinfo="SolutionWithControlInfo"
#   app= "App"
#   project= "Project"
#   user = "User"
#   userdetail = "UserDetail"
#   userscore = "UserScore"
#    codegen = "CodeGen"
#    initdata = "InitData"
#   enumcatalog = "EnumCatalog"
[model2Tbl]
#   Solution="solution"
#   ControlInfo="control_info"
#   App= "xpass_app"
#   Project="project"
#   User = "user"
#   UserDetail = "user_detail"
#   UserScore = "user_score"
#   EnumCatalog="xpass_enum_catalog"
[gfcli]
     [gfcli.build]
         name     = "free-proxy"
         arch     = "amd64"
         system   = "linux"
         mod      = "none"
         cgo      = 0
         pack     = "config,i18n,public,template"
         version  = ""
         output   = "./bin"
         extra    = ""
#      [gfcli.build]
#        name=     "free-proxy"
#        arch=     "amd64"
#        system=   "darwin"
#        mod=      "none"
#        cgo=      0
#        pack=     ""
#        version=  "v1.0.0"
#        output=   "./bin"
#        extra=    ""

    [[gfcli.gen.dao]]
        link     = "mysql:write:write@tcp(43.247.184.35:8899)/xpaas"
        path   = "./app"
        jsonCase = "CamelLower"

[codegen]
apiPath = "/home/jy/dev/backend/gows/src/xpass/app/api/"
servicePath = "/home/jy/dev/backend/gows/src/xpass/app/service/"
daoPath = "/home/jy/dev/backend/gows/src/xpass/app/dao/"
modelPath = "/home/jy/dev/backend/gows/src/xpass/app/model/"



[workflow]
[[flows]]
 name = "testflow1"
 [[flows.tasks]]
   Name=""
   NodeType = 2
   MetaPath=""
 [[flows.tasks]]
   Name=""
   NodeType = 4
   MetaPath=""
[[flows]]


