#多宿主代理配置
[upstreams]
 [[upstreams.hosts]]
    host='t9.com:8000'
    [[upstreams.hosts.backends]]
    ip='192.168.4.1:3000'
    weight=0.5

 [[upstreams.hosts]]
       host='zhiquanquan.com:8000'
       [[upstreams.hosts.backends]]
       ip='192.168.4.1:3003'
       weight=0.5

 [[upstreams.hosts]]
       host='icp.com:8000'
       [[upstreams.hosts.backends]]
       ip='192.168.4.1:3006'
       weight=0.5

  [[upstreams.hosts]]
        host='ic.com:8000'
        [[upstreams.hosts.backends]]
        ip='192.168.4.1:3007'
        weight=0.5

  [[upstreams.hosts]]
     host='192.168.4.1:8000'
     [[upstreams.hosts.backends]]
     ip='192.168.4.1:8190'
     weight=0.5